### ISSUE TITLE
How to add new commands ?

### ISSUE THREAD

**Issue by bcashier** [jaredpetersen/kafka-connect-redis#11]
Hi,

Is there a way to add new commands for sink connector ?

Thank you !

**Comment by jaredpetersen** [comment]
Yes, there definitely is!

There's a few places to touch in the code:
- [Add a command data object that implements RedisCommand](https://github.com/jaredpetersen/kafka-connect-redis/tree/main/src/main/java/io/github/jaredpetersen/kafkaconnectredis/sink/writer/record)
- [Add a record converter function that converts a sink record to the RedisCommand object](https://github.com/jaredpetersen/kafka-connect-redis/blob/main/src/main/java/io/github/jaredpetersen/kafkaconnectredis/sink/writer/RecordConverter.java)
- [Tell Writer what to do with the RedisCommand object once it receives it](https://github.com/jaredpetersen/kafka-connect-redis/blob/main/src/main/java/io/github/jaredpetersen/kafkaconnectredis/sink/writer/Writer.java)

Plus we'd need to add documentation for it:
- [Sink documentation](https://github.com/jaredpetersen/kafka-connect-redis/blob/main/docs/connectors/SINK.md)
- [Demo](https://github.com/jaredpetersen/kafka-connect-redis/blob/main/docs/demo/SINK.md)

Definitely let me know which commands you'd like to see! I'm planning on supporting all of them but since I don't know what people want I'm having trouble figuring out which commands should be prioritized first.

**Comment by bcashier** [comment]
@jaredpetersen Big thanks for your detailed answer !

I need it for a specific plugin of Redis (Redis Time Series), it will be awesome to add datas from kafka topic directly on a time serie database ! This is not part of redis commands but one of plugins that is heavily used on financial services.

Here it is:
https://github.com/RedisTimeSeries/RedisTimeSeries

Is there a way you can implement this in the near future ?

Otherwhise, it will be really interesting to add MULTI ... EXEC ! and also support for SCRIPT LUA !

This last two commands are really useful and used by many !


Thank you again !

**Comment by jaredpetersen** [comment]
Ah, interesting. I'm not familiar with Redis Timeseries but it looks like you install it as a Redis Module so that you can start running commands built in by that module:

```
TS.CREATE temperature:3:11 RETENTION 60 LABELS sensor_id 2 area_id 32
TS.ADD temperature:3:11 1548149181 30
TS.ADD temperature:3:11 1548149191 42
```

And redis-cli even supports those modules. Neat!

I'll have to think about how that should best be supported. I can see two different paths:
- Integrate support for various modules directly into Kafka Connect Redis with its own type-checked record schema. This would work well for open source modules like Redis Timeseries but I'm sure people in the private sector will also want support for their modules without having to fork the code. I can also see this module list growing pretty large in the future.
- Support an arbitrary command feature. This would allow you to pass in a string with whatever you want to run as if you're typing into redis-cli. No type checking of the data structure, so use as your own risk. This could be used by anybody wanting to leverage a Redis module without waiting for support for your specific module. I'm heavily leaning in this direction.

We use lettuce under the hood to communicate with Redis so I'll have to see how arbitrary commands can be supported. It looks like it's [definitely a thing though](https://lettuce.io/core/release/reference/#redis-command-interfaces).

`MULTI ... EXEC` should be pretty doable and I imagine Lua scripts are in that same boat.

I'll start investigating these this week and I'll keep you posted 😄

**Comment by jaredpetersen** [comment]
@bcashier I decided to file some new enhancements for the different items that you requested. I'm digging into the Redis modules feature now and hope to have something released by the end of the week. This is a side project for me though so I appreciate your patience 😄

**Comment by jaredpetersen** [comment]
Closing this out in favor of the enhancement issues.

**Comment by bcashier** [comment]
@jaredpetersen Hi

I like the way you analysed the situation and found the best way to do this !

I think the support an arbitrary command feature is the better way to solve this issue ! but how to be sure that the commands are passed successfully? especially if we take as example MULTI ... EXEC, what if MULTI will not pass and only other following commands be executed ? 

Thanks again and waiting forward to see a result this end of the week !
